FROM node:18-alpine

WORKDIR /app

# Install git and clone the repository
RUN apk add --no-cache git && \
    git clone https://github.com/IrvinTM/urlBitFront.git --depth 1 . && \
    npm install

# Build the React app
RUN npm run build

# Install Nginx
FROM nginx:alpine

# Copy the build output to the Nginx HTML directory
COPY --from=0 /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

