version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_NAME=urldb
      - DB_PASS=examplepassword123
      - DB_USER=postgres
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - TOKEN_PASSWORD=your-token
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: urldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword123